filepaths:
  windows:
    prompts_fp: ".\\prompts.yaml"
    memory_fp: ".\\memory.yaml"
    installer_path: ".\\anki_installer.exe"
    anki_path: ".\\anki\\anki.exe"
    files_path: ".\\files"
    decks_path: ".\\decks"
    text_file: ".\\files\\JÄÄKÄRIJOUKKUEEN+JA+RYHMÄN+KÄSIK_2018_s106_Ryhmän_ryhmittäminen_puolustukseen.pdf"
  linux:
    prompts_fp: "./prompts.yaml"
    memory_fp: "./memory.yaml"
    installer_path: "anki_installer.exe"
    anki_path: "./anki/anki"
    files_path: "./files"
    decks_path: "./decks"
    text_file: "./files/JÄÄKÄRIJOUKKUEEN+JA+RYHMÄN+KÄSIK_2018_s106_Ryhmän_ryhmittäminen_puolustukseen.pdf"

model: "deepseek-r1"
# model: "mistral"
# model: "poro-34b-chat"
# model: "akx/viking-7b"
simple_reply_format: False

options:
  use_readymade_deck: "y"
  readymade_deck_name: "erikoisjoukkue_finnish"
  deck_name: "erikoisjoukkue_finnish"
  topic: "deck for learning finnish words, from english to finnish"
  use_topic_file: "n"
  use_inputs: "n"
  card_amount: "5"
  text: "None"