filepaths:
  task_plan_json_fp: "./task_plan.json"
  prompts_fp: "./prompts.yaml"
  memory_fp: "./memory.yaml"
  anki_path: "C:\\Users\\johnn\\AppData\\Local\\Programs\\Anki\\anki.exe"
  files_path: "C:\\repos\\ai_flash_cards\\files"
# model: "deepseek-r1"
model: "mistral"

options:
  topic: "deck for learning finnish grammar"
  use_file: "n"
  deck_name: "finnish"
  card_amount: "5"
  text: "None"